# ISING
PBIT_NUM_MAX = 128
PBIT_NUM = 100

TERM_WEIGHT_W = 8
TERM_WEIGHT_FRAC = 7

SUM_W = 16
SUM_FRAC = 7

BETA_W = 16
BETA_FRAC = 11

PROBABILITY_W = 12
PROBABILITY_FRAC = 12

# LUT
LUT_INPUT_W = 9
LUT_INPUT_FRAC = 5

LUT_PRODUCT_W = SUM_W + BETA_W
LUT_PRODUCT_FRAC = SUM_FRAC + BETA_FRAC

LUT_SHIFT = LUT_PRODUCT_FRAC - LUT_INPUT_FRAC
LUT_ROUND = 1 << (LUT_SHIFT - 1)

LUT_SCALED_W = LUT_PRODUCT_W - LUT_SHIFT
LUT_SCALED_FRAC = LUT_INPUT_FRAC

LUT_CLAMP_HIGH = (1 << (LUT_INPUT_W - 1)) - 1
LUT_CLAMP_LOW = -(1 << (LUT_INPUT_W - 1))

LUT_BIAS = LUT_INPUT_W - 1

LUT_ADDR_W = LUT_INPUT_W

LUT_DEPTH = 1 << LUT_INPUT_W

# FEEDER
PBITS_PER_PLU = 5
PBITS_PER_PLU_MAX = 16 
TERMS_PER_PBIT_MAX = 32
TERM_TOTAL_MAX = PBITS_PER_PLU_MAX*TERMS_PER_PBIT_MAX

INDEX_W = (PBITS_PER_PLU_MAX-1).bit_length()

PBIT_INDEX_W = (PBIT_NUM_MAX-1).bit_length()
PBIT_PROFILE_ADDRESS_W = (TERM_TOTAL_MAX-1).bit_length()
PBIT_TERM_COUNT_W = (TERMS_PER_PBIT_MAX).bit_length()
INDEX_STRING_W = 1 + PBIT_INDEX_W + PBIT_PROFILE_ADDRESS_W + PBIT_TERM_COUNT_W

TERM_STRING_W = 2 + TERM_WEIGHT_W + 2*PBIT_INDEX_W

# UPDATER
PLU_COUNT = 10
PLU_INDEX_W = (PLU_COUNT-1).bit_length()

# CONTROLLER
COLOR_COUNT_W = (PBITS_PER_PLU-1).bit_length()

ROUND_COUNT = 32768
ROUND_COUNT_W = (ROUND_COUNT).bit_length()

BETA_HOT = 615
BETA_DURATION = 4
BETA_SIGNAL = (BETA_DURATION-1).bit_length()

# DEMUX
if (INDEX_W > PBIT_PROFILE_ADDRESS_W):
    WADDRESS_W = INDEX_W
else:
    WADDRESS_W = PBIT_PROFILE_ADDRESS_W

if (INDEX_STRING_W > TERM_STRING_W):
    WDATA_W = INDEX_STRING_W
else:
    WDATA_W = TERM_STRING_W